#!/usr/bin/env bash
# Sync AI context into per-project config files for each IDE/tool.
#
# Usage:
#   ai-config-sync [OPTIONS] [PROJECT_DIR]
#
# By default only the Claude Code config (.claude/CLAUDE.md) is written.
# Pass tool flags to generate additional configs.
#
# Options:
#   --cursor    Generate .cursorrules for Cursor
#   --windsurf  Generate .windsurfrules for Windsurf
#   --cline     Generate .clinerules for Cline
#   --copilot   Generate .github/copilot-instructions.md for GitHub Copilot
#   --codex     Generate AGENTS.md for OpenAI Codex
#   --all       Enable all of the above
#   -h, --help  Show this help and exit
#
# Source of truth: ~/.config/ai/context.md (your global developer identity).
# Optional per-project rules: .ai/project.md (committed to repo, injected into all tools).
# Claude Code session memory is handled natively by Claude Code auto-memory.
set -euo pipefail

CANONICAL="${HOME}/.config/ai/context.md"

# --- Parse arguments ---
ENABLE_CURSOR=false
ENABLE_WINDSURF=false
ENABLE_CLINE=false
ENABLE_COPILOT=false
ENABLE_CODEX=false
PROJECT_DIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cursor)   ENABLE_CURSOR=true;   shift ;;
        --windsurf) ENABLE_WINDSURF=true; shift ;;
        --cline)    ENABLE_CLINE=true;    shift ;;
        --copilot)  ENABLE_COPILOT=true;  shift ;;
        --codex)    ENABLE_CODEX=true;    shift ;;
        --all)
            ENABLE_CURSOR=true
            ENABLE_WINDSURF=true
            ENABLE_CLINE=true
            ENABLE_COPILOT=true
            ENABLE_CODEX=true
            shift ;;
        -h|--help)
            sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        -*)
            echo "Unknown option: $1" >&2
            echo "Run 'ai-config-sync --help' for usage." >&2
            exit 1 ;;
        *)
            PROJECT_DIR="$1"
            shift ;;
    esac
done

PROJECT_DIR="$(cd "${PROJECT_DIR:-.}" && pwd)"

if [[ ! -f "$CANONICAL" ]]; then
    echo "Error: Canonical context not found at ${CANONICAL}" >&2
    echo "Create it first, or copy templates/context.md and fill in your details." >&2
    exit 1
fi

CONTEXT="$(cat "$CANONICAL")"

# --- Helper ---
write_if_changed() {
    local dest="$1"
    local content="$2"
    local dir
    dir="$(dirname "$dest")"

    mkdir -p "$dir"
    if [[ -f "$dest" ]] && [[ "$(cat "$dest")" == "$content" ]]; then
        echo "  unchanged: ${dest#"$PROJECT_DIR"/}"
        return
    fi
    printf '%s\n' "$content" > "$dest"
    echo "  updated:   ${dest#"$PROJECT_DIR"/}"
}

echo "Syncing AI config into ${PROJECT_DIR}..."

# Load optional per-project rules (.ai/project.md committed to repo).
# Use this for project-specific rules you want in every tool config —
# e.g. "use Bun not npm" or "never edit db/migrations/ directly".
# Most projects won't need this file.
PROJECT_NOTES=""
if [[ -f "${PROJECT_DIR}/.ai/project.md" ]]; then
    PROJECT_NOTES="$(cat "${PROJECT_DIR}/.ai/project.md")"
fi

# --- Claude Code (.claude/CLAUDE.md) ---
# Uses @ syntax: context.md is loaded at session start by Claude Code directly.
# No re-sync needed when context.md changes — the @ reference stays live.
CLAUDE_BODY="# Claude Code — Project Instructions

@~/.config/ai/context.md"

if [[ -n "$PROJECT_NOTES" ]]; then
    CLAUDE_BODY="${CLAUDE_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
fi

write_if_changed "${PROJECT_DIR}/.claude/CLAUDE.md" "$CLAUDE_BODY"

# --- Optional tool configs ---
# These tools cannot load files at runtime, so context is inlined directly.
# Re-run ai-config-sync after updating context.md to refresh these files.

if $ENABLE_CURSOR; then
    CURSOR_BODY="# Cursor Rules
# Auto-generated by ai-config-sync — edit ~/.config/ai/context.md or .ai/project.md

${CONTEXT}"
    if [[ -n "$PROJECT_NOTES" ]]; then
        CURSOR_BODY="${CURSOR_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
    fi
    write_if_changed "${PROJECT_DIR}/.cursorrules" "$CURSOR_BODY"
fi

if $ENABLE_WINDSURF; then
    WINDSURF_BODY="# Windsurf Rules
# Auto-generated by ai-config-sync — edit ~/.config/ai/context.md or .ai/project.md

${CONTEXT}"
    if [[ -n "$PROJECT_NOTES" ]]; then
        WINDSURF_BODY="${WINDSURF_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
    fi
    write_if_changed "${PROJECT_DIR}/.windsurfrules" "$WINDSURF_BODY"
fi

if $ENABLE_CLINE; then
    CLINE_BODY="# Cline Rules
# Auto-generated by ai-config-sync — edit ~/.config/ai/context.md or .ai/project.md

${CONTEXT}"
    if [[ -n "$PROJECT_NOTES" ]]; then
        CLINE_BODY="${CLINE_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
    fi
    write_if_changed "${PROJECT_DIR}/.clinerules" "$CLINE_BODY"
fi

if $ENABLE_COPILOT; then
    COPILOT_BODY="# GitHub Copilot Instructions
<!-- Auto-generated by ai-config-sync — edit ~/.config/ai/context.md or .ai/project.md -->

${CONTEXT}"
    if [[ -n "$PROJECT_NOTES" ]]; then
        COPILOT_BODY="${COPILOT_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
    fi
    write_if_changed "${PROJECT_DIR}/.github/copilot-instructions.md" "$COPILOT_BODY"
fi

if $ENABLE_CODEX; then
    CODEX_BODY="# Codex Agent Instructions
<!-- Auto-generated by ai-config-sync — edit ~/.config/ai/context.md or .ai/project.md -->

${CONTEXT}"
    if [[ -n "$PROJECT_NOTES" ]]; then
        CODEX_BODY="${CODEX_BODY}

## Project-Specific Rules

${PROJECT_NOTES}"
    fi
    write_if_changed "${PROJECT_DIR}/AGENTS.md" "$CODEX_BODY"
fi

# --- Ensure AI config files are gitignored ---
ensure_gitignored() {
    local gitignore="${PROJECT_DIR}/.gitignore"

    if ! git -C "$PROJECT_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
        return
    fi

    local entries=(".claude/")
    $ENABLE_CURSOR   && entries+=(".cursor/" ".cursorrules")
    $ENABLE_WINDSURF && entries+=(".windsurfrules")
    $ENABLE_CLINE    && entries+=(".clinerules")
    $ENABLE_CODEX    && entries+=("AGENTS.md")
    $ENABLE_COPILOT  && entries+=(".github/copilot-instructions.md")

    local missing=()
    for entry in "${entries[@]}"; do
        if ! grep -qxF "$entry" "$gitignore" 2>/dev/null; then
            missing+=("$entry")
        fi
    done

    if [[ ${#missing[@]} -eq 0 ]]; then
        echo "  unchanged: .gitignore"
        return
    fi

    if ! grep -qF "# AI tool configs" "$gitignore" 2>/dev/null; then
        printf '\n# AI tool configs (managed by ai-config-sync)\n' >> "$gitignore"
    fi
    for entry in "${missing[@]}"; do
        printf '%s\n' "$entry" >> "$gitignore"
    done
    echo "  updated:   .gitignore"
}

ensure_gitignored

echo "Done."
